[package]
name = "rice_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.19"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
home = "0.5.4"